import type { Product, Category, Order } from "./types"

// Categories data
export const categories: Category[] = [
  {
    id: "rice-noodles",
    name: "CƠM, MÌ, MIẾN, PHỞ",
    nameEn: "Rice, Noodles & Pho",
    description: "Các món cơm, mì, miến, phở truyền thống và hiện đại",
    image: "/images/categories/category-3.webp",
    order: 1,
  },
  {
    id: "combo",
    name: "Đồ khác (combo)",
    nameEn: "Combo Meals",
    description: "Các phần ăn combo tiện lợi, đa dạng lựa chọn",
    image: "/images/categories/category-10.webp",
    order: 2,
  },
  {
    id: "ccdc",
    name: "Đồ khác CCDC",
    nameEn: "Other Dishes - CCDC",
    description: "Các món đặc biệt và đa dạng theo thực đơn CCDC",
    image: "/images/categories/category-7.webp",
    order: 3,
  },
  {
    id: "drinks",
    name: "Đồ uống mua",
    nameEn: "Beverages",
    description: "Nước ngọt, trà, cà phê và các loại đồ uống đóng chai",
    image: "/images/categories/category-11.webp",
    order: 4,
  },
  {
    id: "fried",
    name: "MÓN CHIÊN",
    nameEn: "Fried Dishes",
    description: "Các món chiên giòn rụm, vàng ươm hấp dẫn",
    image: "/images/categories/category-8.webp",
    order: 5,
  },
  {
    id: "fried-dimsum",
    name: "MÓN CHIÊN - DIMSUM",
    nameEn: "Fried Dim Sum",
    description: "Dimsum chiên phong cách Á Đông, đa dạng hương vị",
    image: "/images/categories/category-12.webp",
    order: 6,
  },
  {
    id: "stewed",
    name: "MÓN HẦM",
    nameEn: "Stewed Dishes",
    description: "Các món hầm mềm ngon, bổ dưỡng và đậm đà",
    image: "/images/categories/category-4.webp",
    order: 7,
  },
  {
    id: "steamed",
    name: "MÓN HẤP",
    nameEn: "Steamed Dishes",
    description: "Các món hấp giữ trọn vị ngọt và dinh dưỡng",
    image: "/images/categories/category-5.webp",
    order: 8,
  },
  {
    id: "seasonal",
    name: "MÓN THEO MÙA",
    nameEn: "Seasonal Dishes",
    description: "Thực đơn đặc biệt theo mùa, tươi ngon và đa dạng",
    image: "/images/categories/category-6.webp",
    order: 9,
  },
  {
    id: "dessert",
    name: "MÓN TRÁNG MIỆNG",
    nameEn: "Desserts",
    description: "Chè, trái cây, bánh ngọt và các món tráng miệng",
    image: "/images/categories/category-9.webp",
    order: 10,
  },
  {
    id: "stir-fried",
    name: "MÓN XÀO",
    nameEn: "Stir-Fried Dishes",
    description: "Các món xào thơm ngon, đậm vị với rau củ và thịt",
    image: "/images/categories/category-2.webp",
    order: 11,
  },
  {
    id: "mixology",
    name: "PHA CHẾ",
    nameEn: "Mixology",
    description: "Nước pha chế độc đáo: mocktail, cocktail, trà sữa,…",
    image: "/images/categories/category-13.webp",
    order: 12,
  },
  {
    id: "soup",
    name: "SÚP CANH TẦN",
    nameEn: "Soup & Herbal Broth",
    description: "Súp, canh tần bổ dưỡng, thơm ngon, tốt cho sức khỏe",
    image: "/images/categories/category-1.webp",
    order: 13,
  },
]

// Products data
export const products: Product[] = [
  // Roasted Poultry
  {
    id: "roasted-1",
    name: "Vịt Quay Bắc Kinh",
    nameEn: "Peking Duck",
    description: "Vịt quay giòn da, thịt mềm, ướp gia vị đặc biệt theo công thức Bắc Kinh truyền thống",
    descriptionEn: "Crispy skin roasted duck with tender meat, marinated with special Beijing recipe",
    price: 450000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: true,
    available: true,
    spicyLevel: 0,
    tags: ["signature", "popular"],
  },
  {
    id: "roasted-2",
    name: "Cơm trắng",
    nameEn: "Steamed Rice",
    description: "Cơm trắng dẻo thơm từ gạo tuyển chọn",
    descriptionEn: "Steamed fragrant rice from selected grains",
    price: 33000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: false,
    available: true,
    spicyLevel: 0,
    tags: ["rice"],
  },
  {
    id: "roasted-3",
    name: "Cơm rang bò băm cay",
    nameEn: "Spicy Minced Beef Fried Rice",
    description: "Cơm rang với bò băm cay đậm đà, thơm ngon",
    descriptionEn: "Fried rice with spicy minced beef, flavorful and savory",
    price: 228000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: false,
    available: true,
    spicyLevel: 2,
    tags: ["fried rice", "beef"],
  },
  {
    id: "roasted-4",
    name: "Cơm rang thịt gà cá mặn",
    nameEn: "Fried Rice with Chicken & Salted Fish",
    description: "Cơm rang kết hợp thịt gà và cá mặn thơm bùi",
    descriptionEn: "Fried rice with chicken and salted fish",
    price: 228000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: false,
    available: true,
    spicyLevel: 1,
    tags: ["fried rice", "chicken", "seafood"],
  },
  {
    id: "roasted-5",
    name: "Cơm rang nhân sò thịt cua lòng trắng trứng",
    nameEn: "Fried Rice with Scallop, Crab & Egg White",
    description: "Cơm rang thượng hạng với sò, cua và lòng trắng trứng",
    descriptionEn: "Premium fried rice with scallops, crab, and egg white",
    price: 328000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: true,
    available: true,
    spicyLevel: 0,
    tags: ["fried rice", "seafood"],
  },
  {
    id: "roasted-6",
    name: "Cơm rang điệp cơ trứng cua",
    nameEn: "Fried Rice with Scallops & Crab Roe",
    description: "Cơm rang hải sản cùng điệp cơ và trứng cua",
    descriptionEn: "Seafood fried rice with scallops and crab roe",
    price: 328000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: true,
    available: true,
    spicyLevel: 0,
    tags: ["fried rice", "seafood"],
  },
  {
    id: "roasted-7",
    name: "Cơm rang hải sản hoàng kim",
    nameEn: "Golden Seafood Fried Rice",
    description: "Cơm rang hải sản với màu sắc vàng óng, hương vị đậm đà",
    descriptionEn: "Golden-style seafood fried rice",
    price: 228000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: false,
    available: true,
    spicyLevel: 0,
    tags: ["fried rice", "seafood"],
  },
  {
    id: "roasted-8",
    name: "Cơm rang hải sản với dứa",
    nameEn: "Seafood Fried Rice with Pineapple",
    description: "Cơm rang hải sản kết hợp dứa chua ngọt",
    descriptionEn: "Seafood fried rice with pineapple",
    price: 228000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: false,
    available: true,
    spicyLevel: 0,
    tags: ["fried rice", "seafood", "pineapple"],
  },
  {
    id: "roasted-9",
    name: "Cơm rang dương châu",
    nameEn: "Yangzhou Fried Rice",
    description: "Cơm rang Dương Châu nổi tiếng, kết hợp nhiều nguyên liệu",
    descriptionEn: "Classic Yangzhou-style fried rice",
    price: 228000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: true,
    available: true,
    spicyLevel: 0,
    tags: ["fried rice", "traditional"],
  },
  {
    id: "roasted-10",
    name: "Phở xào hải sản sốt X.O",
    nameEn: "Stir-fried Pho with Seafood XO Sauce",
    description: "Phở xào hải sản tươi ngon, thấm đẫm sốt X.O đậm đà",
    descriptionEn: "Stir-fried rice noodles with fresh seafood in rich XO sauce",
    price: 228000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: false,
    available: true,
    spicyLevel: 1,
    tags: ["pho", "seafood", "xo sauce"],
  },
  {
    id: "roasted-11",
    name: "Phở xào thịt bò",
    nameEn: "Stir-fried Pho with Beef",
    description: "Phở xào cùng thịt bò mềm, thấm vị đậm đà",
    descriptionEn: "Stir-fried rice noodles with tender beef slices",
    price: 228000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: false,
    available: true,
    spicyLevel: 0,
    tags: ["pho", "beef"],
  },
  {
    id: "roasted-12",
    name: "Mỳ xào thịt lợn sợi",
    nameEn: "Stir-fried Noodles with Pork Strips",
    description: "Mỳ xào thơm ngon cùng thịt lợn sợi mềm vừa",
    descriptionEn: "Stir-fried noodles with tender pork strips",
    price: 228000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: false,
    available: true,
    spicyLevel: 0,
    tags: ["noodles", "pork"],
  },
  {
    id: "roasted-13",
    name: "Mỳ xào thịt bò",
    nameEn: "Stir-fried Noodles with Beef",
    description: "Mỳ xào cùng thịt bò mềm, thấm vị",
    descriptionEn: "Stir-fried noodles with tender beef slices",
    price: 228000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: false,
    available: true,
    spicyLevel: 0,
    tags: ["noodles", "beef"],
  },
  {
    id: "roasted-14",
    name: "Miến xào thịt cua",
    nameEn: "Stir-fried Vermicelli with Crab",
    description: "Miến xào dai ngon, thịt cua ngọt tự nhiên",
    descriptionEn: "Stir-fried vermicelli with fresh crab meat",
    price: 228000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: false,
    available: true,
    spicyLevel: 0,
    tags: ["vermicelli", "crab"],
  },
  {
    id: "roasted-15",
    name: "Miến xào tôm nồi đất",
    nameEn: "Claypot Vermicelli with Shrimp",
    description: "Miến xào cùng tôm tươi, chế biến trong nồi đất giữ trọn hương vị",
    descriptionEn: "Claypot stir-fried vermicelli with fresh shrimp",
    price: 228000,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: true,
    available: true,
    spicyLevel: 0,
    tags: ["vermicelli", "shrimp", "claypot"],
  },
  {
    id: "roasted-16",
    name: "Mỳ",
    nameEn: "Noodles",
    description: "Mỳ cơ bản, dễ ăn, dùng kèm nhiều loại topping",
    descriptionEn: "Basic noodles, versatile for various toppings",
    price: 0,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: false,
    available: true,
    spicyLevel: 0,
    tags: ["noodles"],
  },
  {
    id: "roasted-17",
    name: "Cơm rang",
    nameEn: "Fried Rice",
    description: "Cơm rang cơ bản, có thể chế biến nhiều biến tấu",
    descriptionEn: "Basic fried rice, customizable with various ingredients",
    price: 0,
    image: "/placeholder.svg?height=500&width=500",
    category: "roasted",
    featured: false,
    available: true,
    spicyLevel: 0,
    tags: ["fried rice"],
  },
  // Dim Sum
  {
    id: "dimsum-1",
    name: "Há Cảo Tôm",
    nameEn: "Shrimp Dumplings (Ha Gow)",
    description: "Há cảo tôm tươi, vỏ mỏng trong suốt, nhân tôm ngọt",
    descriptionEn: "Fresh shrimp dumplings with translucent wrapper",
    price: 65000,
    image: "/placeholder.svg?height=500&width=500",
    category: "dimsum",
    featured: true,
    available: true,
    preparationTime: 15,
    spicyLevel: 0,
    tags: ["popular"],
  },
  {
    id: "dimsum-2",
    name: "Sủi Cảo",
    nameEn: "Pork Dumplings (Siu Mai)",
    description: "Sủi cảo nhân thịt heo, tôm, nấm hương thơm ngon",
    descriptionEn: "Pork and shrimp dumplings with shiitake mushroom",
    price: 60000,
    image: "/placeholder.svg?height=500&width=500",
    category: "dimsum",
    featured: true,
    available: true,
    preparationTime: 15,
    spicyLevel: 0,
    tags: ["popular"],
  },
  {
    id: "dimsum-3",
    name: "Bánh Bao Xá Xíu",
    nameEn: "Char Siu Bao",
    description: "Bánh bao nhân thịt xá xíu ngọt, bông xốp",
    descriptionEn: "Steamed buns with sweet char siu pork filling",
    price: 55000,
    image: "/placeholder.svg?height=500&width=500",
    category: "dimsum",
    featured: false,
    available: true,
    preparationTime: 20,
    spicyLevel: 0,
    tags: [],
  },
  {
    id: "dimsum-4",
    name: "Chân Gà Sốt Đen",
    nameEn: "Braised Chicken Feet",
    description: "Chân gà hầm sốt đen đậm đà, mềm ngon",
    descriptionEn: "Braised chicken feet in rich black bean sauce",
    price: 70000,
    image: "/placeholder.svg?height=500&width=500",
    category: "dimsum",
    featured: false,
    available: true,
    preparationTime: 25,
    spicyLevel: 1,
    tags: [],
  },
  {
    id: "dimsum-5",
    name: "Há Cảo Cua",
    nameEn: "Crab Dumplings",
    description: "Há cảo nhân cua tươi, hương vị biển cả",
    descriptionEn: "Fresh crab meat dumplings",
    price: 75000,
    image: "/placeholder.svg?height=500&width=500",
    category: "dimsum",
    featured: false,
    available: true,
    preparationTime: 15,
    spicyLevel: 0,
    tags: [],
  },
  // Noodles
  {
    id: "noodles-1",
    name: "Mì Xào Hải Sản",
    nameEn: "Seafood Fried Noodles",
    description: "Mì xào giòn với tôm, mực, nghêu tươi ngon",
    descriptionEn: "Crispy fried noodles with fresh seafood",
    price: 95000,
    image: "/placeholder.svg?height=500&width=500",
    category: "noodles",
    featured: true,
    available: true,
    preparationTime: 20,
    spicyLevel: 1,
    tags: ["popular"],
  },
  {
    id: "noodles-2",
    name: "Phở Bò Trung Hoa",
    nameEn: "Chinese Beef Noodle Soup",
    description: "Phở bò nước dùng đậm đà, thịt bò mềm, gia vị Trung Hoa",
    descriptionEn: "Beef noodle soup with rich broth and Chinese spices",
    price: 85000,
    image: "/placeholder.svg?height=500&width=500",
    category: "noodles",
    featured: true,
    available: true,
    preparationTime: 25,
    spicyLevel: 2,
    tags: ["signature"],
  },
  {
    id: "noodles-3",
    name: "Mì Vằn Thắn",
    nameEn: "Wonton Noodle Soup",
    description: "Mì trứng với hoành thánh tôm thịt, nước dùng trong",
    descriptionEn: "Egg noodles with pork and shrimp wontons",
    price: 75000,
    image: "/placeholder.svg?height=500&width=500",
    category: "noodles",
    featured: false,
    available: true,
    preparationTime: 20,
    spicyLevel: 0,
    tags: ["popular"],
  },
  {
    id: "noodles-4",
    name: "Mì Xào Thập Cẩm",
    nameEn: "Mixed Fried Noodles",
    description: "Mì xào với thịt, tôm, rau củ đa dạng",
    descriptionEn: "Fried noodles with mixed meat, shrimp and vegetables",
    price: 80000,
    image: "/placeholder.svg?height=500&width=500",
    category: "noodles",
    featured: false,
    available: true,
    preparationTime: 18,
    spicyLevel: 1,
    tags: [],
  },
  // Hot Pot
  {
    id: "hotpot-1",
    name: "Lẩu Tứ Xuyên Cay",
    nameEn: "Spicy Sichuan Hot Pot",
    description: "Lẩu Tứ Xuyên cay nồng, nước dùng đỏ đặc trưng với hoa tiêu",
    descriptionEn: "Spicy Sichuan hot pot with signature red broth and peppercorns",
    price: 350000,
    image: "/placeholder.svg?height=500&width=500",
    category: "hotpot",
    featured: true,
    available: true,
    preparationTime: 30,
    spicyLevel: 5,
    tags: ["signature", "spicy"],
  },
  {
    id: "hotpot-2",
    name: "Lẩu Nấm Chay",
    nameEn: "Vegetarian Mushroom Hot Pot",
    description: "Lẩu nấm chay thanh đạm, nước dùng ngọt từ nấm",
    descriptionEn: "Vegetarian mushroom hot pot with sweet mushroom broth",
    price: 280000,
    image: "/placeholder.svg?height=500&width=500",
    category: "hotpot",
    featured: false,
    available: true,
    preparationTime: 25,
    spicyLevel: 0,
    tags: ["vegetarian"],
  },
  {
    id: "hotpot-3",
    name: "Lẩu Hải Sản",
    nameEn: "Seafood Hot Pot",
    description: "Lẩu hải sản tươi sống, nước dùng ngọt từ xương",
    descriptionEn: "Fresh seafood hot pot with sweet bone broth",
    price: 420000,
    image: "/placeholder.svg?height=500&width=500",
    category: "hotpot",
    featured: true,
    available: true,
    preparationTime: 30,
    spicyLevel: 1,
    tags: ["popular"],
  },
  // Stir Fry
  {
    id: "stirfry-1",
    name: "Tôm Xào Hạt Điều",
    nameEn: "Cashew Nut Shrimp",
    description: "Tôm xào giòn với hạt điều, rau củ tươi",
    descriptionEn: "Stir-fried shrimp with cashew nuts and fresh vegetables",
    price: 145000,
    image: "/placeholder.svg?height=500&width=500",
    category: "stirfry",
    featured: true,
    available: true,
    preparationTime: 15,
    spicyLevel: 1,
    tags: ["popular"],
  },
  {
    id: "stirfry-2",
    name: "Gà Kung Pao",
    nameEn: "Kung Pao Chicken",
    description: "Gà xào cay với đậu phộng, ớt khô đặc trưng Tứ Xuyên",
    descriptionEn: "Spicy chicken stir-fry with peanuts and dried chilies",
    price: 120000,
    image: "/placeholder.svg?height=500&width=500",
    category: "stirfry",
    featured: true,
    available: true,
    preparationTime: 18,
    spicyLevel: 4,
    tags: ["signature", "spicy"],
  },
  {
    id: "stirfry-3",
    name: "Bò Xào Lúc Lắc",
    nameEn: "Shaking Beef",
    description: "Thịt bò thăn xào lúc lắc, mềm ngon",
    descriptionEn: "Tender beef cubes stir-fried with garlic",
    price: 165000,
    image: "/placeholder.svg?height=500&width=500",
    category: "stirfry",
    featured: false,
    available: true,
    preparationTime: 15,
    spicyLevel: 1,
    tags: [],
  },
  {
    id: "stirfry-4",
    name: "Rau Cải Xào Tỏi",
    nameEn: "Garlic Stir-Fried Vegetables",
    description: "Rau cải xanh xào tỏi thơm, giòn ngon",
    descriptionEn: "Fresh green vegetables stir-fried with garlic",
    price: 65000,
    image: "/placeholder.svg?height=500&width=500",
    category: "stirfry",
    featured: false,
    available: true,
    preparationTime: 10,
    spicyLevel: 0,
    tags: ["vegetarian"],
  },
  // Drinks
  {
    id: "drinks-1",
    name: "Trà Ô Long",
    nameEn: "Oolong Tea",
    description: "Trà ô long thơm ngon, thanh mát",
    descriptionEn: "Fragrant oolong tea",
    price: 25000,
    image: "/placeholder.svg?height=500&width=500",
    category: "drinks",
    featured: false,
    available: true,
    preparationTime: 5,
    spicyLevel: 0,
    tags: [],
  },
  {
    id: "drinks-2",
    name: "Trà Sữa Hồng Kông",
    nameEn: "Hong Kong Milk Tea",
    description: "Trà sữa Hồng Kông đậm đà, ngọt vừa",
    descriptionEn: "Rich Hong Kong style milk tea",
    price: 35000,
    image: "/placeholder.svg?height=500&width=500",
    category: "drinks",
    featured: true,
    available: true,
    preparationTime: 5,
    spicyLevel: 0,
    tags: ["popular"],
  },
  {
    id: "drinks-3",
    name: "Nước Dừa Tươi",
    nameEn: "Fresh Coconut Water",
    description: "Nước dừa tươi mát lạnh",
    descriptionEn: "Fresh cold coconut water",
    price: 30000,
    image: "/placeholder.svg?height=500&width=500",
    category: "drinks",
    featured: false,
    available: true,
    preparationTime: 3,
    spicyLevel: 0,
    tags: [],
  },
]

// Mock orders for demo
export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    customerName: "Nguyễn Văn A",
    customerPhone: "0901234567",
    customerEmail: "nguyenvana@email.com",
    deliveryAddress: "47 Cửa Bắc, Ba Đình, Hà Nội",
    items: [
      {
        product: products[0],
        quantity: 1,
      },
      {
        product: products[4],
        quantity: 2,
      },
    ],
    subtotal: 580000,
    deliveryFee: 20000,
    total: 600000,
    status: "preparing",
    paymentMethod: "cash",
    paymentStatus: "pending",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    estimatedDeliveryTime: new Date(Date.now() + 45 * 60000).toISOString(),
  },
]
